export const PLATFORM_TYPES = {
  OUTLOOK: 'OUTLOOK',
  OUTLOOK_365: 'OUTLOOK_365',
  THUNDERBIRD: 'THUNDERBIRD',
  GMAIL: 'GMAIL',
  EXCHANGE_SERVER: 'EXCHANGE_SERVER',
  EXCHANGE_ONLINE: 'EXCHANGE_ONLINE',
};
